name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  main:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir: ["1.13.0", "1.14.0"]
        otp: ["24.0", "25.0"]
    defaults:
      run:
        working-directory: ${{ matrix.working_directory }}
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Retrieve dependencies cache
        env:
          cache-name: cache-mix-deps
        uses: actions/cache@v3
        id: mix-cache # id to use in retrieve action
        with:
          path: ${{ github.workspace }}/${{ matrix.working_directory }}/deps
          key: ${{ runner.os }}-Elixir-v${{ matrix.elixir }}-OTP-${{ matrix.otp }}-${{ hashFiles(format('{0}/{1}/mix.lock', github.workspace, matrix.working_directory)) }}
      - name: Install dependencies
        if: ${{ steps.mix-cache.outputs.cache-hit != 'true' }}
        run: mix deps.get
      - name: Compile and check warnings
        run: mix compile --warnings-as-errors
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run tests
        run: mix test
